version: "3"

vars:
  LOCALBIN: "{{.ROOT_DIR}}/bin"
  CONTROLLER_GEN_VERSION: '{{ .CONTROLLER_GEN_VERSION | default "v0.21.0" }}'
  CONTROLLER_GEN: "{{.LOCALBIN}}/controller-gen"
  ENVTEST_VERSION: '{{ .ENVTEST_VESRION | default "v0.24.0" }}'
  ENVTEST_K8S_VERSION: '{{ .ENVTEST_K8S_VESRION | default "1.36.0" }}'
  ENVTEST_SETUP: "{{.LOCALBIN}}/setup-envtest"

tasks:
  gen:install:
    desc: Install controller-gen locally
    generates:
      - "{{.CONTROLLER_GEN}}"
    run: once
    cmds:
      - mkdir -p {{.LOCALBIN}}
      - GOBIN={{.LOCALBIN}} go install sigs.k8s.io/controller-tools/cmd/controller-gen@{{.CONTROLLER_GEN_VERSION}}

  test:generate:
    desc: gen code + manifests
    deps:
      - gen:install
    cmds:
      - task: test:gen:code
      - task: test:gen:manifests
      - task: test:gen:code
        vars:
          PATHS: ./testdata/config/...
      - task: test:gen:manifests
        vars:
          PATHS: ./testdata/config/...
          OUTPUT: ./testdata/config/crd/bases

  test:gen:code:
    desc: Generate deepcopy methods and CRDs for the test API
    vars:
      PATHS: '{{ .PATHS | default "./testdata/api/..."}}'
    deps:
      - gen:install
    cmds:
      - >
        {{.CONTROLLER_GEN}} object paths={{.PATHS}}

  test:gen:manifests:
    desc: Generate deepcopy methods and CRDs for the test API
    vars:
      PATHS: '{{ .PATHS | default "./testdata/api/..."}}'
      OUTPUT: '{{ .OUTPUT | default "./testdata/api/crd/bases"}}'
    deps:
      - gen:install
    cmds:
      - rm -rf {{.OUTPUT}}
      - >
        {{.CONTROLLER_GEN}} crd paths={{.PATHS}} output:crd:artifacts:config={{.OUTPUT}}

  envtest:install:
    desc: Install setup-envtest locally
    generates:
      - "{{.ENVTEST_SETUP}}"
    run: once
    cmds:
      - mkdir -p {{.LOCALBIN}}
      - GOBIN={{.LOCALBIN}} go install sigs.k8s.io/controller-runtime/tools/setup-envtest@{{.ENVTEST_VERSION}}

  envtest:setup:
    desc: Run setup-envtest
    deps:
      - envtest:install
    cmds:
      - >
        {{.ENVTEST_SETUP}} use {{.ENVTEST_K8S_VERSION}} --bin-dir {{.LOCALBIN}}
